import { test, expect } from '@playwright/test';
async function mount(page, extra='') {
 await page.route('**/feedback-test',r=>r.fulfill({contentType:'text/html',body:`<html><head><meta name="viewport" content="width=device-width,initial-scale=1"></head><body><div id="root"></div><script type="module">import '/@vite/client';import RefreshRuntime from '/@react-refresh';RefreshRuntime.injectIntoGlobalHook(window);window.$RefreshReg$=()=>{};window.$RefreshSig$=()=>(type)=>type;window.__vite_plugin_react_preamble_installed__=true;const React=(await import('/node_modules/.vite/deps/react.js')).default;const DOM=(await import('/node_modules/.vite/deps/react-dom_client.js')).default;const Viewer=(await import('/src/components/FeedbackViewer.jsx')).default;await import('/src/index.css');window.saved=[];window.fail=false;const props={isDeveloper:true,eventId:'event-test',entries:[{id:'a',kind:'feedback',by:'Alice',note:'Settings scrolling',createdAt:2},{id:'b',kind:'feedback',by:'Bob',note:'Team order',createdAt:1},{id:'c',kind:'other',note:'Hidden field observation'}],loadStatuses:async()=>[{feedback_id:'b',status:'resolved'}],saveStatus:async(...args)=>{if(window.fail)throw Error('offline');window.saved.push(args);},onClose:()=>{}};${extra}DOM.createRoot(document.getElementById('root')).render(React.createElement(Viewer,props));</script></body></html>`}));await page.goto('/feedback-test');
}
test('triage saves, filters, preserves messages and fails without optimistic status',async({page})=>{
 await mount(page);await expect(page.getByLabel('Status for Alice')).toHaveValue('new');await expect(page.getByLabel('Status for Bob')).toHaveValue('resolved');await expect(page.getByText('Hidden field observation')).toHaveCount(0);
 await page.getByLabel('Status for Alice').selectOption('in_progress');await expect(page.getByRole('status')).toContainText('marked In progress');expect(await page.evaluate(()=>window.saved)).toEqual([['event-test','a','in_progress']]);
 await page.getByLabel('Filter by status').selectOption('resolved');await expect(page.getByText('Settings scrolling')).toHaveCount(0);await expect(page.getByText('Team order')).toBeVisible();await page.getByLabel('Filter by status').selectOption('all');
 await page.getByLabel('Search feedback').fill('alice');await expect(page.getByText('Team order')).toHaveCount(0);await page.evaluate(()=>window.fail=true);await page.getByLabel('Status for Alice').selectOption('resolved');await expect(page.getByRole('status')).toContainText('not saved');await expect(page.getByLabel('Status for Alice')).toHaveValue('in_progress');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('load failure blocks edits and refresh recovers',async({page})=>{await mount(page,`let calls=0;props.loadStatuses=async()=>{if(!calls++)throw Error('missing migration');return [];};`);await expect(page.getByRole('alert')).toBeVisible();await expect(page.getByLabel('Status for Alice')).toBeDisabled();await page.getByRole('button',{name:'Refresh statuses'}).click();await expect(page.getByLabel('Status for Alice')).toBeEnabled();});
test('non-developer cannot see feedback or invoke status loader',async({page})=>{await mount(page,`props.isDeveloper=false;props.loadStatuses=async()=>{window.loaded=true;return [];};`);await expect(page.getByRole('heading',{name:'View Feedback'})).toHaveCount(0);expect(await page.evaluate(()=>window.loaded)).toBeUndefined();});
