import {test,expect} from '@playwright/test';
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==','base64');
async function mount(page,body){await page.route('**/screenshots-test',r=>r.fulfill({contentType:'text/html',body:`<html><head><meta name="viewport" content="width=device-width,initial-scale=1"></head><body><div id="root"></div><script type="module">import '/@vite/client';import RefreshRuntime from '/@react-refresh';RefreshRuntime.injectIntoGlobalHook(window);window.$RefreshReg$=()=>{};window.$RefreshSig$=()=>(type)=>type;window.__vite_plugin_react_preamble_installed__=true;const React=(await import('/node_modules/.vite/deps/react.js')).default;const DOM=(await import('/node_modules/.vite/deps/react-dom_client.js')).default;await import('/src/index.css');${body}</script></body></html>`}));await page.goto('/screenshots-test');}
test('real screenshot compression previews, removal, max count and stable retry submission',async({page})=>{
 await mount(page,`const Modal=(await import('/src/components/modals/FeedbackModal.jsx')).default;window.submissions=[];let first=true;DOM.createRoot(document.getElementById('root')).render(React.createElement(Modal,{meName:'Tester',onClose:()=>{},onSubmit:async(entry,shots)=>{window.submissions.push({id:entry.id,note:entry.note,shots:shots.length,mime:shots[0]?.mime});if(first){first=false;throw Error('Message saved; retry screenshots');}}}));`);
 await page.getByLabel('Feedback message').fill('Mobile menu issue');const input=page.getByLabel('Attach screenshots',{exact:true});await input.setInputFiles({name:'screen.png',mimeType:'image/png',buffer:png});await expect(page.getByAltText('Selected screenshot 1')).toBeVisible();await page.screenshot({path:test.info().outputPath('feedback-screenshot-preview.png'),fullPage:true});await page.getByRole('button',{name:'Remove screenshot 1'}).click();await expect(page.getByAltText('Selected screenshot 1')).toHaveCount(0);
 await input.setInputFiles(Array.from({length:4},(_,i)=>({name:`shot${i}.png`,mimeType:'image/png',buffer:png})));await expect(page.getByRole('alert')).toContainText('up to three');await input.setInputFiles({name:'screen.png',mimeType:'image/png',buffer:png});await expect(page.getByAltText('Selected screenshot 1')).toBeVisible();await page.getByRole('button',{name:'Send Feedback',exact:true}).click();await expect(page.getByRole('alert')).toContainText('retry');await expect(input).toBeDisabled();await page.getByRole('button',{name:'Send Feedback',exact:true}).click();await expect(page.getByText('Feedback Sent',{exact:true})).toBeVisible();const rows=await page.evaluate(()=>window.submissions);expect(rows).toHaveLength(2);expect(rows[0].id).toBe(rows[1].id);expect(rows[1].shots).toBe(1);expect(['image/webp','image/jpeg']).toContain(rows[1].mime);
});
test('unsupported file gets inline error and no preview',async({page})=>{await mount(page,`const Modal=(await import('/src/components/modals/FeedbackModal.jsx')).default;DOM.createRoot(document.getElementById('root')).render(React.createElement(Modal,{onClose:()=>{},onSubmit:()=>{}}));`);await page.getByLabel('Attach screenshots',{exact:true}).setInputFiles({name:'file.pdf',mimeType:'application/pdf',buffer:Buffer.from('not an image')});await expect(page.getByRole('alert')).toContainText('PNG');await expect(page.getByAltText('Selected screenshot 1')).toHaveCount(0);});
test('attachment viewer retries failures and shows private screenshot',async({page})=>{await mount(page,`const View=(await import('/src/components/FeedbackAttachments.jsx')).default;let calls=0;DOM.createRoot(document.getElementById('root')).render(React.createElement(View,{feedbackId:'a',loadScreenshots:async()=>{if(!calls++)throw Error('Connection failed');return [{slot:0,url:'data:image/png;base64,${png.toString('base64')}'}];}}));`);await page.getByRole('button',{name:'View screenshots'}).click();await expect(page.getByRole('alert')).toContainText('Connection');await page.getByRole('button',{name:'View screenshots'}).click();await expect(page.getByAltText('Feedback screenshot 1')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);});
test('actual submission API retries with same id and skips registered attachments',async({page})=>{
 await mount(page,`window.ready=true;`);let submissions=[];let registered=false;let uploads=0;let linkAttempts=0;
 await page.route('https://example.supabase.co/rest/v1/rpc/submit_feedback_with_screenshots',r=>{submissions.push(r.request().postDataJSON());return r.fulfill({status:204});});
 await page.route('https://example.supabase.co/rest/v1/feedback_attachments**',r=>r.fulfill({contentType:'application/json',body:JSON.stringify(registered?[{slot:0,path:'e/u/id/0.jpg'}]:[])}));
 await page.route('https://example.supabase.co/storage/v1/object/feedback-screenshots/**',r=>{uploads++;return r.fulfill({status:uploads===1?200:400,contentType:'application/json',body:JSON.stringify(uploads===1?{Key:'test'}:{statusCode:'409',message:'already exists'})});});
 await page.route('https://example.supabase.co/rest/v1/rpc/register_feedback_screenshot',r=>{linkAttempts++;if(linkAttempts===1)return r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({message:'offline'})});registered=true;return r.fulfill({status:204});});
 const result=await page.evaluate(async()=>{const {supabase}=await import('/src/supabaseClient.js');supabase.auth.getUser=async()=>({data:{user:{id:'u'}}});const api=await import('/src/feedbackScreenshots.js');const submission={eventId:'e',id:'id',note:'issue',by:'Tester',sessionId:'session',screenshots:[{mime:'image/jpeg',blob:new Blob(['bytes'],{type:'image/jpeg'})}]};let error;try{await api.submitFeedbackScreenshots(submission);}catch(e){error=e.message;}await api.submitFeedbackScreenshots(submission);await api.submitFeedbackScreenshots(submission);return error;});expect(result).toContain('message was saved');expect(submissions).toHaveLength(3);expect(new Set(submissions.map(s=>s.p_id)).size).toBe(1);expect(submissions[0].p_session).toBe('session');expect(uploads).toBe(2);expect(linkAttempts).toBe(2);
});
test('signed screenshot links use private bucket and expire after ten minutes',async({page})=>{
 await mount(page,`window.ready=true;`);let signBody;
 await page.route('https://example.supabase.co/rest/v1/feedback_attachments**',r=>r.fulfill({contentType:'application/json',body:JSON.stringify([{slot:1,path:'event/user/feedback/1.jpg'}])}));
 await page.route('https://example.supabase.co/storage/v1/object/sign/feedback-screenshots/**',r=>{signBody=r.request().postDataJSON();return r.fulfill({contentType:'application/json',body:JSON.stringify({signedURL:'/object/sign/feedback-screenshots/private.jpg?token=test'})});});
 const result=await page.evaluate(async()=>{const api=await import('/src/feedbackScreenshots.js');return await api.loadFeedbackScreenshots('feedback');});expect(signBody.expiresIn).toBe(600);expect(result[0].slot).toBe(1);expect(result[0].url).toContain('/object/sign/feedback-screenshots/');
});
