import {test,expect} from '@playwright/test';
test('practice entries are temporary, clearable, and do not persist',async({page})=>{
 await page.route('**/practice-test',route=>route.fulfill({contentType:'text/html',body:`<html><body><div id="root"></div><script type="module">
 import '/@vite/client';import RefreshRuntime from '/@react-refresh';RefreshRuntime.injectIntoGlobalHook(window);window.$RefreshReg$=()=>{};window.$RefreshSig$=()=>(type)=>type;window.__vite_plugin_react_preamble_installed__=true;
 const React=(await import('/node_modules/.vite/deps/react.js')).default;const ReactDOM=(await import('/node_modules/.vite/deps/react-dom_client.js')).default;const Practice=(await import('/src/components/HighlanderPractice.jsx')).default;
 const root=ReactDOM.createRoot(document.getElementById('root'));window.mountPractice=key=>root.render(React.createElement(Practice,{key,by:'Demo',renderForm:({onSave,onClose})=>React.createElement('div',null,React.createElement('button',{onClick:()=>onSave({newNumber:'2a',notes:'Fake observation',ruleGroups:[{type:'minor',code:'G1',desc:'Example'},{type:'major',code:'G2',desc:'Second example'}]})},'Add example'),React.createElement('button',{onClick:onClose},'Cancel example')),renderEntry:(entry,remove)=>React.createElement('li',{key:entry.id},entry.team+' '+entry.code+' '+entry.notes,React.createElement('button',{onClick:remove},'Remove '+entry.code))}));window.mountPractice(1);
 </script></body></html>`}));
 await page.goto('/practice-test');const before=await page.evaluate(()=>JSON.stringify({...localStorage}));
 await page.getByRole('button',{name:'Log practice violation'}).click();await page.getByRole('button',{name:'Cancel example'}).click();await expect(page.getByRole('listitem')).toHaveCount(0);
 await page.getByRole('button',{name:'Log practice violation'}).click();await page.getByRole('button',{name:'Add example'}).click();await expect(page.getByRole('listitem')).toHaveCount(2);await expect(page.getByRole('status')).toContainText('Not saved');await page.getByRole('button',{name:'Remove G1'}).click();await expect(page.getByRole('listitem')).toHaveCount(1);await page.getByRole('button',{name:'Clear practice entries'}).click();await expect(page.getByRole('listitem')).toHaveCount(0);
 await page.getByRole('button',{name:'Log practice violation'}).click();await page.getByRole('button',{name:'Add example'}).click();await page.evaluate(()=>window.mountPractice(2));await expect(page.getByRole('listitem')).toHaveCount(0);expect(await page.evaluate(()=>JSON.stringify({...localStorage}))).toBe(before);
});
