import {test,expect} from '@playwright/test';
import {readFileSync} from 'node:fs';
import {transformSync} from 'esbuild';
const source=readFileSync(new URL('../src/App.jsx',import.meta.url),'utf8');
const list=source.slice(source.indexOf('function robotPhotoAngle('),source.indexOf('// League events: inspection pictures',source.indexOf('function robotPhotoAngle(')));
const detail=source.slice(source.indexOf('function RobotDetail('),source.indexOf('/* ============================ JUDGING',source.indexOf('function RobotDetail(')));
const component=transformSync(`import React from '/node_modules/.vite/deps/react.js';const {useState,useRef,useContext}=React;import {Camera,Search,Trash2} from '/node_modules/.vite/deps/lucide-react.js';import {ROBOT_PHOTO_SLOTS,normalizeRequiredRobotPhotos,robotPhotoSlots} from '/src/robotPhotoRequirements.js';const LeagueUiContext=React.createContext(null);const Empty=({title})=>React.createElement('p',null,title);const Thumb=()=>React.createElement('div');const IQInspectionChecklist=()=>null;const LeagueEarlierRobotPhotos=()=>null;const compressRobotPhoto=async()=>({dataUrl:'data:image/jpeg;base64,aA=='});const createPortal=(child)=>child;${list.replace('function RobotList(','export function RobotList(')}${detail.replace('function RobotDetail(','export function RobotDetail(')}`,{loader:'jsx',format:'esm'}).code;
async function mount(page,body){await page.route('**/robot-component.js',r=>r.fulfill({contentType:'text/javascript',body:component}));await page.route('**/photo-settings-test',r=>r.fulfill({contentType:'text/html',body:`<html><head><meta name="viewport" content="width=device-width,initial-scale=1"></head><body><div id="root"></div><script type="module">import '/@vite/client';import RefreshRuntime from '/@react-refresh';RefreshRuntime.injectIntoGlobalHook(window);window.$RefreshReg$=()=>{};window.$RefreshSig$=()=>(type)=>type;window.__vite_plugin_react_preamble_installed__=true;const React=(await import('/node_modules/.vite/deps/react.js')).default;const DOM=(await import('/node_modules/.vite/deps/react-dom_client.js')).default;await import('/src/index.css');${body}</script></body></html>`}));await page.goto('/photo-settings-test');}
test('settings save photo-only changes and allow no required photos',async({page})=>{
 await mount(page,`const Modal=(await import('/src/components/modals/EventSettingsModal.jsx')).default;window.saved=[];DOM.createRoot(document.getElementById('root')).render(React.createElement(Modal,{event:{id:'e',name:'Event'},brand:{name:'Event',shortName:'Event',accent:'#2563EB'},onClose:()=>{},onSave:args=>window.saved.push(args)}));`);
 await expect(page.getByRole('checkbox',{name:'Front',exact:true})).toBeChecked();await expect(page.getByRole('checkbox',{name:'Lexan Diagram'})).not.toBeChecked();await page.getByRole('checkbox',{name:'Lexan Diagram'}).check();await page.getByRole('checkbox',{name:'Back',exact:true}).uncheck();await page.getByRole('button',{name:'Save Settings'}).click();await expect.poll(()=>page.evaluate(()=>window.saved[0]?.requiredRobotPhotos)).toEqual(['front','side','tag','lexan']);
 await page.reload();for(const label of ['Front','Side','Back','Inspection Tag'])await page.getByRole('checkbox',{name:label,exact:true}).uncheck();await page.getByRole('button',{name:'Save Settings'}).click();await expect.poll(()=>page.evaluate(()=>window.saved[0]?.requiredRobotPhotos)).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('robot list and detail use event choices, pending photos and optional-only state',async({page})=>{
 await mount(page,`const Views=await import('/robot-component.js');const team={number:'123A',photoKeys:['/event/front-id.jpg'],_pendingRobotPhotos:[{id:'queued',angle:'lexan',dataUrl:'data:image/jpeg;base64,aA=='}]};function App(){const [required,setRequired]=React.useState(['lexan']);window.none=()=>setRequired([]);return React.createElement(React.Fragment,null,React.createElement(Views.RobotList,{requiredRobotPhotos:required,teams:[team],query:'',setQuery:()=>{},onOpen:()=>{}}),React.createElement(Views.RobotDetail,{requiredRobotPhotos:required,isIQ:true,team,canTakePhotos:false,canDeletePhotos:false}));}DOM.createRoot(document.getElementById('root')).render(React.createElement(App));`);
 await expect(page.getByText('1/1',{exact:true})).toBeVisible();await expect(page.getByText('Required pictures complete',{exact:true})).toBeVisible();await expect(page.getByText('Lexan Diagram',{exact:true})).toBeVisible();await page.evaluate(()=>window.none());await expect(page.getByText('Optional',{exact:true}).first()).toBeVisible();await expect(page.getByText('No pictures required',{exact:true})).toBeVisible();await expect(page.getByText('Lexan Diagram',{exact:true})).toHaveCount(0);
});
test('camera sequence starts with required Lexan and keeps its snapshot during settings changes',async({page})=>{
 await mount(page,`const Views=await import('/robot-component.js');window.saved=[];function App(){const [required,setRequired]=React.useState(['lexan']);window.change=()=>setRequired(['front']);return React.createElement(Views.RobotDetail,{requiredRobotPhotos:required,team:{number:'123A',photoKeys:[]},onAddPhoto:(n,data,angle)=>window.saved.push(angle)});}DOM.createRoot(document.getElementById('root')).render(React.createElement(App));`);
 await page.getByRole('button',{name:'Take pictures in order'}).click();await expect(page.getByRole('button',{name:'Open camera: Take Lexan Diagram picture'})).toBeVisible();await page.evaluate(()=>window.change());await expect(page.getByRole('button',{name:'Open camera: Take Lexan Diagram picture'})).toBeVisible();await page.locator('input[type=file]').setInputFiles({name:'photo.jpg',mimeType:'image/jpeg',buffer:Buffer.from('stub')});await expect.poll(()=>page.evaluate(()=>window.saved)).toEqual(['lexan']);await expect(page.getByRole('button',{name:'Open camera: Take Front picture'})).toBeVisible();
});
test('Inspection requirements API is event scoped and restores cached empty selections',async({page})=>{
 await page.route(/\/src\/api(?:\.js)?(?:\?.*)?$/,async r=>{const res=await r.fetch();await r.fulfill({response:res,body:(await res.text()).replace('const E2E_MOCK = import.meta.env.VITE_E2E_MOCK === "1";','const E2E_MOCK = false;')});});await mount(page,`window.ready=true;`);let failed=false;await page.route('https://example.supabase.co/rest/v1/rpc/get_event_robot_photo_requirements',r=>failed?r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({message:'offline'})}):r.fulfill({contentType:'application/json',body:JSON.stringify({required:[]})}));
 const first=await page.evaluate(async()=>{const api=await import('/src/api.js');return api.getEventRobotPhotoRequirements('event-a');});expect(first.value.required).toEqual([]);failed=true;expect(await page.evaluate(async()=>{const api=await import('/src/api.js');return (await api.getEventRobotPhotoRequirements('event-a')).value.required;})).toEqual([]);expect(await page.evaluate(async()=>{const api=await import('/src/api.js');try{await api.getEventRobotPhotoRequirements('event-b');return false;}catch{return true;}})).toBe(true);
});
