import {test,expect} from '@playwright/test';
import {readFileSync} from 'node:fs';
import {transformSync} from 'esbuild';
const source=readFileSync(new URL('../src/App.jsx',import.meta.url),'utf8');
const phases=source.slice(source.indexOf('const MATCH_PHASES ='),source.indexOf('const splitRuleCodes'));
const modal=source.slice(source.indexOf('function LogModal('),source.indexOf('/* ============================ RULE PICKER'));
const moduleText=transformSync(`import {parseViolationRuleNotes,validViolationRuleDetails,formatViolationRuleNotes} from '/src/violationRuleNotes.js';import React from '/node_modules/.vite/deps/react.js';const {useState,useMemo,useRef}=React;import {X,Camera,Plus,UserCircle2,AlertTriangle,ShieldAlert,ClipboardCheck} from '/node_modules/.vite/deps/lucide-react.js';const ORDER=['minor','major','inspection'];const TYPES=Object.fromEntries(ORDER.map(key=>[key,{label:key,Icon:AlertTriangle}]));const Label=({children})=>React.createElement('p',null,children);const Thumb=()=>null;const normNum=value=>String(value||'').trim().toUpperCase();const splitRuleCodes=value=>String(value||'').split('|').filter(Boolean);const splitRuleDescs=value=>String(value||'').split('|');const fmtRule=value=>value;const fieldDisplayName=value=>value;const DEFAULT_FIELD_NAMES=[];const RulePicker=({onPickRule,onClose})=>React.createElement('button',{onClick:()=>{onPickRule(window.testRule||'G1','Conduct');onClose();}},'Use test rule');${phases}${modal.replace('function LogModal(','export default function LogModal(')}`,{loader:'jsx',format:'esm'}).code;
async function mount(page,scoped=true){await page.route('**/skills-log.js',r=>r.fulfill({contentType:'text/javascript',body:moduleText}));await page.route('**/skills-test',r=>r.fulfill({contentType:'text/html',body:`<html><head><meta name="viewport" content="width=device-width,initial-scale=1"></head><body><div id="root"></div><script type="module">import '/src/index.css';const React=(await import('/node_modules/.vite/deps/react.js')).default;const ReactDOM=(await import('/node_modules/.vite/deps/react-dom_client.js')).default;const Modal=(await import('/skills-log.js')).default;ReactDOM.createRoot(document.getElementById('root')).render(React.createElement(Modal,{teams:[{number:'1069A',name:'Team'}],presetTeam:${scoped?"'1069A'":"null"},viols:[],knownRules:{},me:{name:'Staff'},event:{id:'event'},matches:{},rules:[],onSave:async data=>{window.saved=data;},onClose:()=>{}}));</script></body></html>`}));await page.goto('/skills-test');}
for(const phase of ['skills_driver','skills_auto'])test(`${phase} can be saved from team history without scheduled matches`,async({page})=>{
 await mount(page);const select=page.locator('select').filter({has:page.locator(`option[value="${phase}"]`)});await select.selectOption(phase);await page.getByLabel('Skills run number (optional)').fill('2');await page.getByRole('button',{name:'Select rules',exact:true}).click();await page.getByRole('button',{name:'Use test rule'}).click();await page.getByRole('button',{name:'Save violation',exact:true}).click();await expect.poll(()=>page.evaluate(()=>window.saved?.match)).toEqual({phase,num:'2'});await expect(page.getByText(/No scheduled matches/)).toHaveCount(0);
});
test('general violation form allows an unspecified Skills run without a run number',async({page})=>{
 await mount(page,false);await page.locator('select').filter({has:page.locator('option[value="skills"]')}).selectOption('skills');await page.getByRole('button',{name:'Select rules',exact:true}).click();await page.getByRole('button',{name:'Use test rule'}).click();await page.getByRole('button',{name:'Save violation',exact:true}).click();await expect.poll(()=>page.evaluate(()=>window.saved?.match)).toEqual({phase:'skills',num:''});
});
