import {test,expect} from '@playwright/test';
async function mount(page,developer=true){
 await page.route('**/universal-test',r=>r.fulfill({contentType:'text/html',body:`<html><head><meta name="viewport" content="width=device-width,initial-scale=1"></head><body><div id="root"></div><script type="module">import '/@vite/client';import RefreshRuntime from '/@react-refresh';RefreshRuntime.injectIntoGlobalHook(window);window.$RefreshReg$=()=>{};window.$RefreshSig$=()=>(type)=>type;window.__vite_plugin_react_preamble_installed__=true;const React=(await import('/node_modules/.vite/deps/react.js')).default;const DOM=(await import('/node_modules/.vite/deps/react-dom_client.js')).default;const View=(await import('/src/components/UniversalFeedback.jsx')).default;await import('/src/index.css');window.saved=[];window.loads=0;const rows=[{id:'a',kind:'feedback',eventId:'1',eventName:'Event One',sessionName:'Session 1',by:'Alice',note:'First issue',status:'new',createdAt:2},{id:'b',kind:'feedback',eventId:'2',eventName:'Archived Event Two',sessionName:'',by:'Bob',note:'Second issue',status:'resolved',createdAt:1}];DOM.createRoot(document.getElementById('root')).render(React.createElement(View,{events:[{id:'1',name:'Event One'}],claimAccess:async()=>({developer:${developer}}),listFeedback:async()=>{window.loads++;return rows;},saveStatus:async(...args)=>window.saved.push(args),onClose:()=>{}}));</script></body></html>`}));await page.goto('/universal-test');
}
test('universal viewer signs in once, labels and filters events, saves and refreshes',async({page})=>{
 await mount(page);await page.getByLabel('Developer code').fill('fixture-secret');await page.getByRole('button',{name:'Open all feedback'}).click();await expect(page.getByRole('heading',{name:'Universal Feedback'})).toBeVisible();await expect(page.getByText('First issue')).toBeVisible();await expect(page.getByText('Second issue')).toBeVisible();await page.screenshot({path:test.info().outputPath('universal-feedback.png'),fullPage:true});
 await page.getByLabel('Filter by event').selectOption('2');await expect(page.getByText('First issue')).toHaveCount(0);await expect(page.getByRole('article').getByText('Archived Event Two',{exact:true})).toBeVisible();await page.getByLabel('Status for Bob').selectOption('in_progress');await expect(page.getByRole('status')).toContainText('marked In progress');expect(await page.evaluate(()=>window.saved)).toEqual([[undefined,'b','in_progress']]);
 const before=await page.evaluate(()=>window.loads);await page.getByRole('button',{name:'Refresh statuses'}).click();await expect.poll(()=>page.evaluate(()=>window.loads)).toBeGreaterThan(before);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('ordinary Admin cannot load universal feedback',async({page})=>{await mount(page,false);await page.getByLabel('Developer code').fill('fixture-admin');await page.getByRole('button',{name:'Open all feedback'}).click();await expect(page.getByRole('alert')).toBeVisible();expect(await page.evaluate(()=>window.loads)).toBe(0);await expect(page.getByLabel('Developer code')).toHaveValue('');});
test('main event screen exposes universal feedback without entering workspace',async({page})=>{await page.goto('/');await page.getByRole('button',{name:'Universal Feedback · Developer only'}).click();await expect(page.getByRole('heading',{name:'Universal Feedback'})).toBeVisible();await expect(page.getByLabel('Developer code')).toBeVisible();await page.getByRole('button',{name:'Back to Choose VEX Event'}).click();await expect(page.getByRole('button',{name:'Universal Feedback · Developer only'})).toBeVisible();});
test('actual API maps feedback and loads beyond one page, then sends status RPC',async({page})=>{
 await mount(page);let pages=0;let saved;
 await page.route('https://example.supabase.co/rest/v1/rpc/list_universal_feedback**',r=>{pages++;const offset=Number(new URL(r.request().url()).searchParams.get('offset') || 0);const count=offset===0?500:1;return r.fulfill({contentType:'application/json',body:JSON.stringify(Array.from({length:count},(_,i)=>({id:`row-${offset+i}`,event_id:'event-a',event_name:'Event A',session_name:'Session 2',note:'Issue',logged_by:'Sender',created_at:'2026-10-05T12:00:00Z',status:'new'})))});});
 await page.route('https://example.supabase.co/rest/v1/rpc/set_universal_feedback_status**',r=>{saved=r.request().postDataJSON();return r.fulfill({status:204});});
 const result=await page.evaluate(async()=>{const api=await import('/src/api.js');const rows=await api.listUniversalFeedback();await api.setUniversalFeedbackStatus(null,rows[500].id,'resolved');return {length:rows.length,kind:rows[0].kind,event:rows[0].eventName,session:rows[0].sessionName};});expect(result).toEqual({length:501,kind:'feedback',event:'Event A',session:'Session 2'});expect(pages).toBe(2);expect(saved).toEqual({p_feedback:'row-500',p_status:'resolved'});
});
