import React,{useState} from 'react';
import {IQ_LEVELS,iqScore,iqTeams,iqMatchName,iqFinalPairs,parseIQMatches} from './iqWorkflows.js';
const button='min-h-[44px] rounded-lg border border-slate-300 dark:border-slate-600 px-3 py-2 font-semibold text-sm';
const input='w-full min-h-[44px] rounded-lg border border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-800 px-3 py-2';

export function IQScoreAid({onSave,canSave=false,initialScore=null}){
 const [counts,setCounts]=useState({}),[manual,setManual]=useState(initialScore==null?'':String(initialScore)),[mode,setMode]=useState('counts'),[busy,setBusy]=useState(false),[status,setStatus]=useState('');
 let score=null,error='';try{score=mode==='counts'?iqScore(counts):Number(manual);if(mode==='manual'&&(!manual.trim()||!Number.isInteger(score)||score<0))throw new Error('Enter a whole, non-negative shared score.');}catch(e){error=e.message;}
 async function save(){setBusy(true);setStatus('');try{await onSave(score);setStatus('Shared score saved in Ref OS. Record the official result in Tournament Manager.');}catch(e){setStatus(e.message||'Score could not be saved.');}finally{setBusy(false);}}
 return <section className="space-y-3 rounded-xl border border-slate-200 dark:border-slate-700 p-4">
  <h3 className="font-bold">Level Up scoring aid</h3><p className="text-sm">Evaluate the settled field after the match (SC1–SC5). Count each bag once at its highest qualifying level. Only yellow bags count on L4. This aid does not decide scoring eligibility or change Tournament Manager.</p>
  <label className="block text-sm">Score entry<select className={input} value={mode} onChange={e=>{setMode(e.target.value);setStatus('');}}><option value="counts">Count scored bags</option><option value="manual">Enter reviewed shared score</option></select></label>
  {mode==='counts'?<div className="grid grid-cols-1 sm:grid-cols-2 gap-3">{IQ_LEVELS.map(level=><label key={level.key} className="block text-sm">{level.label} · {level.points} points each<input className={input} type="number" inputMode="numeric" min="0" max={level.key==='l4'?6:38} step="1" value={counts[level.key]??''} onChange={e=>{setCounts({...counts,[level.key]:e.target.value});setStatus('');}}/></label>)}</div>:<label className="block text-sm">Shared score<input className={input} type="number" min="0" step="1" inputMode="numeric" value={manual} onChange={e=>{setManual(e.target.value);setStatus('');}}/></label>}
  {error?<p role="alert" className="text-red-700 dark:text-red-300">{error}</p>:<p className="font-bold" aria-live="polite">Shared total: {score}</p>}
  {canSave&&<button className={button} disabled={busy||!!error} onClick={save}>{busy?'Saving…':'Save shared score'}</button>}
  {status&&<p role="status" className="text-sm">{status}</p>}
 </section>;
}

export function IQMatchDetail({match,teamName={},viols=[],fieldLog=[],canEdit=false,onSaveScore,onLogTeam,onAddField}){
 const [note,setNote]=useState(''),[kind,setKind]=useState('other'),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);
 if(!match)return <p>Match not found.</p>;
 if(iqTeams(match).length>2 || match.blueScore!=null)return <p role="alert">This is an opposing-alliance schedule. Import the IQ teamwork schedule before recording an IQ score.</p>;
 const partners=iqTeams(match),entries=fieldLog.filter(e=>e.matchId===match.id);
 async function log(){setBusy(true);try{await onAddField({kind,matchId:match.id,matchRef:iqMatchName(match),field:match.field||'',note:note.trim()});setNote('');setStatus('Field observation saved.');}catch(e){setStatus(e.message||'Could not save observation.');}finally{setBusy(false);}}
 return <section className="space-y-4"><h2 className="text-xl font-bold">IQ Teamwork · {iqMatchName(match)}</h2><p>{match.field||'Field not set'} · {match.label}</p><p className="text-lg font-bold">Shared score: {match.redScore==null?'Not scored':match.redScore}</p>
  <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">{partners.map(number=><div className="rounded-xl border p-4" key={number}><p className="font-bold">Partner {number}</p><p>{teamName[number]||''}</p>{onLogTeam&&<button className={button} onClick={()=>onLogTeam(number)}>Log violation for {number}</button>}</div>)}</div>
  <div className="rounded-xl bg-sky-50 dark:bg-sky-950/40 p-4 text-sm"><h3 className="font-bold">Referee quick checks</h3><ul className="list-disc pl-5 space-y-1"><li>Teamwork lasts 60 seconds; both partners contribute to one score.</li><li>Check legal starting size and positions before starting (R3, SG1).</li><li>Drivers exchange the controller with 0:35–0:25 remaining; one driver cannot operate longer than 35 seconds (GG11).</li><li>Stop inputs at 0:00; allow objects released before the end to settle (GG12, SC1).</li><li>No autonomous bonus, AWP, opposing-alliance timeout, or elimination advancement applies to this teamwork match.</li><li>Photographs are robot reference/evidence records, not a way to overturn a match scoring ruling (SC2, T3).</li></ul></div>
  <IQScoreAid key={match.id} initialScore={match.redScore} canSave={canEdit} onSave={score=>onSaveScore(match,score)}/>
  {onAddField&&<section className="space-y-2"><h3 className="font-bold">Field observation</h3><label className="block text-sm">Observation type<select className={input} value={kind} onChange={e=>setKind(e.target.value)}><option value="other">Other / readiness</option><option value="field_fault">Field fault</option><option value="replay">Replay ruling</option></select></label><label className="block text-sm">What happened<textarea className={input} value={note} onChange={e=>setNote(e.target.value)}/></label><p className="text-sm">Record a replay only after the Head Referee and Event Partner make the ruling under GG5. Logging a replay does not create a replacement match.</p><button className={button} disabled={busy||!note.trim()} onClick={log}>Save field observation</button>{status&&<p role="status">{status}</p>}</section>}
  <section><h3 className="font-bold">This match's records</h3>{entries.map(e=><p key={e.id} className="text-sm">{e.kind}: {e.note}</p>)}{viols.filter(v=>v.match?.phase===match.phase&&Number(v.match?.num)===Number(match.num)).map(v=><p key={v.id} className="text-sm">{v.team} · {v.code} · {v.notes}</p>)}</section>
 </section>;
}

export default function IQMatches({target='Current event / session',matches={},teams=[],finals=false,query='',setQuery=()=>{},onOpen,canEdit=false,onImport,onCreateFinals,parseCSV}){
 const [preview,setPreview]=useState(null),[count,setCount]=useState('5'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const all=Object.values(matches),rows=all.filter(m=>finals?m.phase==='final':true).filter(m=>(iqMatchName(m)+' '+iqTeams(m).join(' ')+' '+(m.field||'')).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>({practice:0,qual:1,final:2}[a.phase]-{practice:0,qual:1,final:2}[b.phase])||Number(a.num)-Number(b.num));
 async function read(file){if(!file)return;setPreview(null);setError('');try{const parsed=parseIQMatches(await file.text(),file.name,parseCSV);setPreview({rows:parsed,kind:'import'});}catch(e){setError(e.message);}}
 function pair(){setPreview(null);setError('');try{const pairs=iqFinalPairs(teams,count);if(all.some(m=>m.phase==='final'))throw new Error('Finals already exist. Import the reviewed TM finals schedule to update them.');setPreview({rows:pairs,kind:'finals'});}catch(e){setError(e.message);}}
 async function apply(){setBusy(true);setError('');try{if(preview.kind==='finals')await onCreateFinals(preview.rows);else await onImport(preview.rows);setPreview(null);}catch(e){setError((e.message||'Could not save.')+' Some rows may have saved. Review and retry.');}finally{setBusy(false);}}
 const scoredFinals=all.filter(m=>m.phase==='final'&&m.redScore!=null).sort((a,b)=>Number(b.redScore)-Number(a.redScore));
 return <section className="space-y-4">
  <p className="text-sm">{finals?'Finals pair adjacent official ranks: 1 + 2, 3 + 4, and so on (T12). Lowest seed plays first; each partnership plays one finals match. Highest score wins, with T14 tiebreakers resolved in Tournament Manager.':'IQ teamwork has two partner teams and one shared score. Import the official schedule and results from Tournament Manager.'}</p>
  <label className="block text-sm">Search IQ matches<input className={input} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Match, team or field"/></label>
  {canEdit&&<label className="block text-sm">Import IQ schedule / results<input className={input} type="file" accept=".csv,.json" disabled={busy} onChange={e=>{const f=e.target.files[0];e.target.value='';read(f);}}/><span className="block mt-1">CSV: Round, Match, Team1, Team2, Field, Score. Use Qualification, Practice or Finals for Round. Score is optional; blank scores keep saved results.</span></label>}
  {finals&&canEdit&&<div className="flex flex-wrap gap-2 items-end"><label className="block text-sm">Number of finals matches<input className={input} type="number" min="1" step="1" value={count} onChange={e=>setCount(e.target.value)}/></label><button className={button} disabled={busy} onClick={pair}>Preview ranked finals pairings</button></div>}
  {error&&<p role="alert" className="text-red-700 dark:text-red-300">{error}</p>}
  {preview&&<section aria-label="IQ import preview" className="rounded-xl border p-4 space-y-3"><h3 className="font-bold">Review {preview.rows.length} IQ matches</h3><p className="text-sm">Target: {target}. Matching match numbers are updated; omitted matches remain. Review partner teams before saving. Finals previews are provisional until confirmed by the Event Partner in TM.</p><ul>{preview.rows.map(m=><li key={m.phase+':'+m.num}>{iqMatchName(m)} · {iqTeams(m).join(' + ')} · {m.label} · {m.redScore==null?'score unchanged':`score ${m.redScore}`}</li>)}</ul><button className={button} disabled={busy} onClick={apply}>{busy?'Saving…':'Apply IQ matches'}</button><button className={button} disabled={busy} onClick={()=>setPreview(null)}>Cancel preview</button></section>}
  {finals&&scoredFinals.length>0&&<section className="rounded-xl border p-4"><h3 className="font-bold">Recorded finals scores</h3><p className="text-sm">Listed by score, not a declaration of the champion. Resolve first-place ties through tiebreaker matches, stop times, and seeds under T14. Import each tiebreaker with a distinct finals match number.</p><ol>{scoredFinals.map(m=><li key={m.id}>{iqTeams(m).join(' + ')} · {m.redScore} · {iqMatchName(m)} · {m.label}</li>)}</ol></section>}
  {!rows.length?<p>No IQ matches loaded. Import the schedule to begin.</p>:<ul className="space-y-2">{rows.map(m=><li key={m.id}><button className="w-full min-h-[60px] text-left rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 p-4" onClick={()=>onOpen(m.id)}><span className="font-bold">{iqMatchName(m)} · {iqTeams(m).join(' + ')}</span><span className="block text-sm">{m.field} {m.label} · Shared score: {m.redScore==null?'Not scored':m.redScore}</span></button></li>)}</ul>}
 </section>;
}

export function IQInspectionChecklist(){
 const [checked,setChecked]=useState({});
 const checks=[['R3','Measure starting size: 11 × 20 × 15 inches (279.4 × 508 × 381 mm).'],['R4','Check legal, readable team license plates.'],['R6–R11','Check one IQ Brain, current legal firmware, at most six Smart Motors, legal battery, and one Controller.'],['R12–R17','Review IQ parts, permitted non-IQ items, decorations, pneumatics and modifications against the manual.'],['R2','Confirm inspection and required reinspection with the inspector before play.']];
 return <section className="rounded-xl border border-sky-200 dark:border-sky-800 p-4 mb-4"><h3 className="font-bold">IQ inspection preparation</h3><p className="text-sm mb-3">A temporary checklist for this screen. It does not certify inspection or replace the official inspection form. Photo completion records pictures, not a pass.</p>{checks.map(([code,text])=><label className="flex items-start gap-3 min-h-[44px] py-2 text-sm" key={code}><input type="checkbox" checked={!!checked[code]} onChange={e=>setChecked({...checked,[code]:e.target.checked})}/><span><b>{code}</b> · {text}</span></label>)}</section>;
}
