import React,{useEffect,useState} from 'react';
import {claimEventAccess} from '../api';
import {listLiveActivity} from '../liveActivity';
export default function DeveloperLiveActivity({events=[],isDeveloper=false,onClose,load=listLiveActivity,claim=claimEventAccess}){
 const [verified,setVerified]=useState(isDeveloper),[code,setCode]=useState(''),[event,setEvent]=useState(events.find(e=>!e.archivedAt)?.id||''),[rows,setRows]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[updated,setUpdated]=useState(null);
 useEffect(()=>{if(!verified)return;let live=true,flight=false;const refresh=async()=>{if(flight||document.hidden)return;flight=true;try{const next=await load();if(live){setRows(next);setUpdated(new Date());setError('');}}catch(e){if(live){setRows([]);setError(e.message);}}finally{flight=false;}};refresh();const timer=setInterval(refresh,15000);document.addEventListener('visibilitychange',refresh);return()=>{live=false;clearInterval(timer);document.removeEventListener('visibilitychange',refresh);};},[verified,load]);
 const signIn=async e=>{e.preventDefault();setBusy(true);try{const access=await claim(event,code);setCode('');if(!access.developer)throw Error('Developer access required.');await load();setVerified(true);setError('');}catch{setCode('');setError('Could not verify Developer access. Check your code and connection.');}finally{setBusy(false);}};
 return <section className="space-y-4 rounded-xl border bg-white p-4 dark:bg-slate-800">{onClose&&<button type="button" onClick={onClose} className="min-h-[44px] font-semibold">Back</button>}<h2 className="text-xl font-bold">Live user activity · Developer only</h2><p className="text-sm">Current screens and broad actions across events. Refreshes every 15 seconds. Background tabs are marked; disconnected devices disappear after 90 seconds. Draft text, photos and access codes are not collected. This is a status view, not a screen recording or cursor sharing.</p>{error&&<p role="alert" className="text-red-700 dark:text-red-300">{error}</p>}
 {!verified?<form onSubmit={signIn} className="space-y-3"><label className="block">Sign-in event<select value={event} onChange={e=>setEvent(e.target.value)} className="block min-h-[44px] w-full rounded border bg-transparent p-2">{events.filter(e=>!e.archivedAt).map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><label className="block">Developer code<input type="password" autoComplete="off" value={code} onChange={e=>setCode(e.target.value)} className="block min-h-[44px] w-full rounded border bg-transparent p-2"/></label><button disabled={busy||!event||!code.trim()} className="min-h-[44px] rounded bg-sky-800 px-4 text-white">{busy?'Checking access…':'View live activity'}</button></form>:<><p className="text-sm">{rows.length} connected devices{updated?` · updated ${updated.toLocaleTimeString()}`:''}</p>{!rows.length&&!error&&<p>No connected users reporting activity yet.</p>}<div className="grid gap-3 sm:grid-cols-2">{rows.map(row=><article key={row.device_id} className="rounded-lg border p-3"><h3 className="font-bold">{row.display_name}</h3><p className="text-sm">{row.event_name}{row.session_name?` · ${row.session_name}`:''}</p><p className="mt-2">{row.screen} · {row.activity}</p><p className="text-xs text-slate-500">{row.visible?'App visible':'Background tab'} · last update {new Date(row.updated_at).toLocaleTimeString()}</p></article>)}</div></>}
 </section>;
}
